### ISSUE TITLE
Mac OS Crash on key press

### ISSUE THREAD

**Issue by julian-weinert** [jawi/ols#246]
I'm having trouble with the current version (0.9.7.2) of the Mac OS client.
It runs well, except when I try to use the keyboard for anything.

The issue is a function deprecated in OS X 10.12, `CGSEventRecord`. It appears as if the application was built using Java 1.6 and the issue should be fixed in 1.8.

Here is the crash log
```
Client version  : 0.9.7.2
Java information: Apple Inc. v1.6.0_65
Host information: Mac OS X, 10.13.6 (x86_64)

Stack trace: 
-----
java.lang.RuntimeException: Non-Java exception raised, not handled! (Original problem: Deprecated in 10_12... DO NOT EVER USE CGSEventRecord directly. Bad things, man.... bad things.)
	at apple.awt.ComponentModel._handleEvent(Native Method)
	at apple.awt.ComponentModel.handleEvent(ComponentModel.java:273)
	at apple.awt.CWindow.handleEvent(CWindow.java:545)
	at java.awt.DefaultKeyboardFocusManager.dispatchKeyEvent(DefaultKeyboardFocusManager.java:753)
	at java.awt.DefaultKeyboardFocusManager.preDispatchKeyEvent(DefaultKeyboardFocusManager.java:1000)
	at java.awt.DefaultKeyboardFocusManager.typeAheadAssertions(DefaultKeyboardFocusManager.java:865)
	at java.awt.DefaultKeyboardFocusManager.dispatchEvent(DefaultKeyboardFocusManager.java:686)
	at java.awt.Component.dispatchEventImpl(Component.java:4648)
	at java.awt.Container.dispatchEventImpl(Container.java:2142)
	at java.awt.Window.dispatchEventImpl(Window.java:2492)
	at java.awt.Component.dispatchEvent(Component.java:4604)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:717)
	at java.awt.EventQueue.access$400(EventQueue.java:82)
	at java.awt.EventQueue$2.run(EventQueue.java:676)
	at java.awt.EventQueue$2.run(EventQueue.java:674)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.AccessControlContext$1.doIntersectionPrivilege(AccessControlContext.java:86)
	at java.security.AccessControlContext$1.doIntersectionPrivilege(AccessControlContext.java:97)
	at java.awt.EventQueue$3.run(EventQueue.java:690)
	at java.awt.EventQueue$3.run(EventQueue.java:688)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.AccessControlContext$1.doIntersectionPrivilege(AccessControlContext.java:86)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:687)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:296)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:211)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:205)
	at java.awt.Dialog$1.run(Dialog.java:1049)
	at java.awt.Dialog$3.run(Dialog.java:1101)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.awt.Dialog.show(Dialog.java:1099)
	at java.awt.Component.show(Component.java:1615)
	at java.awt.Component.setVisible(Component.java:1567)
	at java.awt.Window.setVisible(Window.java:846)
	at java.awt.Dialog.setVisible(Dialog.java:984)
	at nl.lxtreme.ols.util.swing.component.JErrorDialog.showDialog(JErrorDialog.java:525)
	at nl.lxtreme.ols.util.swing.component.JErrorDialog$SwingUncaughtExceptionHandler$1.run(JErrorDialog.java:410)
	at nl.lxtreme.ols.util.swing.component.JErrorDialog$SwingUncaughtExceptionHandler.uncaughtException(JErrorDialog.java:416)
	at java.lang.ThreadGroup.uncaughtException(ThreadGroup.java:981)
	at java.lang.ThreadGroup.uncaughtException(ThreadGroup.java:976)
	at apple.awt.CToolkit$EventQueueExceptionHandler.handle(CToolkit.java:81)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:39)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25)
	at java.lang.reflect.Method.invoke(Method.java:597)
	at java.awt.EventDispatchThread.handleException(EventDispatchThread.java:412)
	at java.awt.EventDispatchThread.processException(EventDispatchThread.java:318)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:312)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:211)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:201)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:196)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:188)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:122)

-----
```

**Comment by partsdotpdf** [comment]
I also had this issue with 0.9.7.2 and compiled from source to get the latest and this issue was resolved.
