### ISSUE TITLE
Client fails to run on Linux & Windows using JDK 7

### ISSUE THREAD

**Issue by wayoda** [jawi/ols#75]
After updating my java installation to JDK7 (provided by Oracle) on Ubuntu 11.04 the Client does not start up any more. There is a long list of errors printed to the console (see end of this posting) an then the process hangs. The application window is never displayed .
Switching back to JDK6 proved that the Client runs on the older Java version.    

Here are the first 10% of the errors printed to the console.   

```
wayoda@rebooter:~/lab/ols/downloads/updates/ols-0308/jawis-ols-client$ ./run.sh 
ERROR: Bundle nl.lxtreme.ols.export.image [3] Error starting file:/home/wayoda/lab/ols/downloads/updates/ols-0308/jawis-ols-client/plugins/image-1.0.0.jar (org.osgi.framework.BundleException: Unresolved constraint in bundle nl.lxtreme.ols.export.image [3]: Unable to resolve 3.0: missing requirement [3.0] package; (package=javax.imageio))
org.osgi.framework.BundleException: Unresolved constraint in bundle nl.lxtreme.ols.export.image [3]: Unable to resolve 3.0: missing requirement [3.0] package; (package=javax.imageio)
        at org.apache.felix.framework.Felix.resolveBundle(Felix.java:3446)
        at org.apache.felix.framework.Felix.startBundle(Felix.java:1734)
        at org.apache.felix.framework.Felix.setActiveStartLevel(Felix.java:1163)
        at org.apache.felix.framework.StartLevelImpl.run(StartLevelImpl.java:264)
        at java.lang.Thread.run(Thread.java:722)
ERROR: Bundle org.rxtx [5] Error starting file:/home/wayoda/lab/ols/downloads/updates/ols-0308/jawis-ols-client/plugins/org.rxtx-2.2.0-9.jar (org.osgi.framework.BundleException: Unresolved constraint in bundle org.rxtx [5]: Unable to resolve 5.0: missing requirement [5.0] package; (package=nl.lxtreme.ols.util) [caused by: Unable to resolve 17.0: missing requirement [17.0] package; (package=javax.accessibility)])
org.osgi.framework.BundleException: Unresolved constraint in bundle org.rxtx [5]: Unable to resolve 5.0: missing requirement [5.0] package; (package=nl.lxtreme.ols.util) [caused by: Unable to resolve 17.0: missing requirement [17.0] package; (package=javax.accessibility)]
        at org.apache.felix.framework.Felix.resolveBundle(Felix.java:3446)
        at org.apache.felix.framework.Felix.startBundle(Felix.java:1734)
        at org.apache.felix.framework.Felix.setActiveStartLevel(Felix.java:1163)
        at org.apache.felix.framework.StartLevelImpl.run(StartLevelImpl.java:264)
        at java.lang.Thread.run(Thread.java:722)
ERROR: Bundle nl.lxtreme.ols.client [6] Error starting file:/home/wayoda/lab/ols/downloads/updates/ols-0308/jawis-ols-client/plugins/client-1.1.0.jar (org.osgi.framework.BundleException: Unresolved constraint in bundle nl.lxtreme.ols.client [6]: Unable to resolve 6.0: missing requirement [6.0] package; (package=javax.swing.border))
org.osgi.framework.BundleException: Unresolved constraint in bundle nl.lxtreme.ols.client [6]: Unable to resolve 6.0: missing requirement [6.0] package; (package=javax.swing.border)
        at org.apache.felix.framework.Felix.resolveBundle(Felix.java:3446)
        at org.apache.felix.framework.Felix.startBundle(Felix.java:1734)
        at org.apache.felix.framework.Felix.setActiveStartLevel(Felix.java:1163)
        at org.apache.felix.framework.StartLevelImpl.run(StartLevelImpl.java:264)
        at java.lang.Thread.run(Thread.java:722)
ERROR: Bundle nl.lxtreme.ols.tool.base [7] Error starting file:/home/wayoda/lab/ols/downloads/updates/ols-0308/jawis-ols-client/plugins/base-1.0.0.jar (org.osgi.framework.BundleException: Unresolved constraint in bundle nl.lxtreme.ols.tool.base [7]: Unable to resolve 7.0: missing requirement [7.0] package; (package=javax.swing.filechooser))
org.osgi.framework.BundleException: Unresolved constraint in bundle nl.lxtreme.ols.tool.base [7]: Unable to resolve 7.0: missing requirement [7.0] package; (package=javax.swing.filechooser)
        at org.apache.felix.framework.Felix.resolveBundle(Felix.java:3446)
        at org.apache.felix.framework.Felix.startBundle(Felix.java:1734)
        at org.apache.felix.framework.Felix.setActiveStartLevel(Felix.java:1163)
        at org.apache.felix.framework.StartLevelImpl.run(StartLevelImpl.java:264)
        at java.lang.Thread.run(Thread.java:722)
ERROR: Bundle nl.lxtreme.ols.tool.i2c [9] Error starting file:/home/wayoda/lab/ols/downloads/updates/ols-0308/jawis-ols-client/plugins/i2c-1.0.1.jar (org.osgi.framework.BundleException: Unresolved constraint in bundle nl.lxtreme.ols.tool.i2c [9]: Unable to resolve 9.0: missing requirement [9.0] package; (package=nl.lxtreme.ols.api) [caused by: Unable to resolve 21.0: missing requirement [21.0] package; (package=nl.lxtreme.ols.util) [caused by: Unable to resolve 17.0: missing requirement [17.0] package; (package=javax.accessibility)]])
org.osgi.framework.BundleException: Unresolved constraint in bundle nl.lxtreme.ols.tool.i2c [9]: Unable to resolve 9.0: missing requirement [9.0] package; (package=nl.lxtreme.ols.api) [caused by: Unable to resolve 21.0: missing requirement [21.0] package; (package=nl.lxtreme.ols.util) [caused by: Unable to resolve 17.0: missing requirement [17.0] package; (package=javax.accessibility)]]
        at org.apache.felix.framework.Felix.resolveBundle(Felix.java:3446)
        at org.apache.felix.framework.Felix.startBundle(Felix.java:1734)
        at org.apache.felix.framework.Felix.setActiveStartLevel(Felix.java:1163)
        at org.apache.felix.framework.StartLevelImpl.run(StartLevelImpl.java:264)
        at java.lang.Thread.run(Thread.java:722)
ERROR: Bundle nl.lxtreme.ols.tool.uart [10] Error starting file:/home/wayoda/lab/ols/downloads/updates/ols-0308/jawis-ols-client/plugins/uart-1.0.0.jar (org.osgi.framework.BundleException: Unresolved constraint in bundle nl.lxtreme.ols.tool.uart [10]: Unable to resolve 10.0: missing requirement [10.0] package; (package=nl.lxtreme.ols.api) [caused by: Unable to resolve 21.0: missing requirement [21.0] package; (package=nl.lxtreme.ols.util) [caused by: Unable to resolve 17.0: missing requirement [17.0] package; (package=javax.accessibility)]])
org.osgi.framework.BundleException: Unresolved constraint in bundle nl.lxtreme.ols.tool.uart [10]: Unable to resolve 10.0: missing requirement [10.0] package; (package=nl.lxtreme.ols.api) [caused by: Unable to resolve 21.0: missing requirement [21.0] package; (package=nl.lxtreme.ols.util) [caused by: Unable to resolve 17.0: missing requirement [17.0] package; (package=javax.accessibility)]]
        at org.apache.felix.framework.Felix.resolveBundle(Felix.java:3446)
        at org.apache.felix.framework.Felix.startBundle(Felix.java:1734)
        at org.apache.felix.framework.Felix.setActiveStartLevel(Felix.java:1163)
        at org.apache.felix.framework.StartLevelImpl.run(StartLevelImpl.java:264)
        at java.lang.Thread.run(Thread.java:722)
```

Eberhard

**Comment by ericwilk** [comment]
This is still a problem for me on Linux mypcname-C55D-A 3.13.0-37-generic #64-Ubuntu SMP Mon Sep 22 21:28:38 UTC 2014 x86_64 x86_64 x86_64 GNU/Linux

... when /usr/bin/java is pointed to jdk 7. I had to download 6 and change run.sh to point to that java to get it to run. Also, it seems like there are some problems with the OLS updater script (backslashes in the cp won't work for Linux I don't think and it isn't going to escape the colon).

Regardless, I can get it to work by hacking the script files but wanted to open this since it was marked as 'resolved' so long ago.

**Comment by DGxInfinitY** [comment]
Same problem still with Oracle Java 8.

**Comment by martinayotte** [comment]
Right ! I'm facing the same issue !
I would like to avoid getting to install an old java-1.6 ...
